FROM rust:1.46-stretch as builder

RUN USER=root cargo new --lib bragi-status
WORKDIR ./bragi-status
COPY ./Cargo.toml ./Cargo.toml

RUN cargo build --lib --release
RUN rm src/*.rs

ADD . ./

RUN rm ./target/release/deps/bragi-status*
RUN cargo build --release

FROM rust:1.46-stretch
ARG APP=/usr/src/app

RUN apt-get update \
    && apt-get install -y ca-certificates tzdata \
    && rm -rf /var/lib/apt/lists/*

ENV TZ=Etc/UTC \
    RUN_MODE=development \
    APP_USER=appuser

RUN groupadd $APP_USER \
    && useradd -g $APP_USER $APP_USER \
    && mkdir -p ${APP}

COPY --from=builder /ctl2mimir/target/release/service ${APP}/service
COPY --from=builder /ctl2mimir/config ${APP}/config
COPY --from=builder /ctl2mimir/docker/entrypoint.sh ${APP}/entrypoint.sh

RUN chown -R $APP_USER:$APP_USER ${APP}

USER $APP_USER
WORKDIR ${APP}

CMD ["./entrypoint.sh"]
