FROM rust:1.46-buster as builder

RUN USER=root cargo new --lib bragi-status
WORKDIR ./bragi-status
COPY ./Cargo.toml ./Cargo.toml
RUN apt-get update \
    && apt-get install -y ca-certificates tzdata \
    && apt-get install -y libjq1 libjq-dev libonig5 libonig-dev \
    && rm -rf /var/lib/apt/lists/*
ENV JQ_LIB_DIR=/usr/lib/x86_64-linux-gnu

RUN cargo build --lib --release
RUN rm src/*.rs

ADD . ./

RUN rm ./target/release/deps/bragi_status*
RUN cargo build --release

FROM debian:buster-slim
ARG APP=/usr/src/app

RUN apt-get update \
    && apt-get install -y ca-certificates tzdata \
    && rm -rf /var/lib/apt/lists/*

ENV TZ=Etc/UTC \
    RUN_MODE=development \
    APP_USER=appuser

RUN groupadd $APP_USER \
    && useradd -g $APP_USER $APP_USER \
    && mkdir -p ${APP}

COPY --from=builder /bragi-status/target/release/service ${APP}/service
COPY --from=builder /bragi-status/config ${APP}/config
COPY --from=builder /bragi-status/docker/entrypoint.sh ${APP}/entrypoint.sh

RUN chown -R $APP_USER:$APP_USER ${APP}

USER $APP_USER
WORKDIR ${APP}

CMD ["./entrypoint.sh"]
